// import { useEffect } from 'react'
// import { globalStateContext } from '../../contexts/ContextProvider'

import Head from 'next/head'
import Link from 'next/link'

import { Button } from 'antd'
import { Login } from '../../components/forms'

const Auth = () => {
  // const { globalFunctions } = globalStateContext()
  // const { checkAuth, validateAuth } = globalFunctions

  // useEffect(() => {
  //   checkAuth()
  //   validateAuth()
  // }, [])

  return (
    <>
      <Head>
        <title>Autentikasi Flipped Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col px-5 py-2 bg-gray-800 items-center justify-center space-y-10 text-white">
        <div className="flex w-full space-x-10 justify-center">
          <div className="w-20 h-20 bg-gray-200" />
          <div className="w-20 h-20 bg-gray-200" />
        </div>
        <p className="font-bold text-xl md:text-2xl lg:text-3xl text-center tracking-wide">
          Login Flipped Learning
        </p>
        <div className="flex flex-col w-[90%] md:w-[70%] lg:w-[35%] space-y-2">
          <Login />

          <div className="flex flex-col w-full text-sm items-center">
            <p className='text-sm text-white mb-0'>Belum punya akun?</p>
            <Link href="/auth/register">
              <Button type="link" className="w-full">
                <p className="font-semibold text-base text-white hover:text-blue-500 cursor-pointer duration-150">
                  Daftar
                </p>
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}

export default Auth
