import Head from 'next/head'
import Link from 'next/link'

import { RegisterForm } from '../../components/authentication/forms'

const Register = () => {
  return (
    <div>
      <Head>
        <title>Pendaftaran Pengguna Flipped Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto h-full flex flex-col px-5 py-10 bg-gray-800 items-center justify-center space-y-10 text-white">
        <div className="flex w-full space-x-10 justify-center lg:justify-start">
          <div className="w-20 h-20 bg-gray-200" />
          <div className="w-20 h-20 bg-gray-200" />
        </div>
        <p className="font-bold text-xl md:text-2xl lg:text-3xl text-center tracking-wide">
          Pendaftaran Pengguna Flipped Learning
        </p>
        <div className="flex flex-col w-[80%] md:w-[30%] space-y-2">
          <RegisterForm />
          <Link href='/auth' className="flex flex-col space-y-2 items-center text-white">
              <button className="text-base font-semibold mb-0 hover:text-blue-500 duration-150 cursor-pointer">Kembali ke Login</button>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Register
