export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ForgotPage } from './ForgotPage'
export { default as VerifyPage } from './VerifyPage'
export { default as ResetPasswordPage } from './ResetPasswordPage'
