import Head from 'next/head'

import { Form, Input, Button, Select, DatePicker, Checkbox } from 'antd'

export default function Register () {
  const onFinish = (values) => {
    console.log('Success:', values)
  }

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo)
  }

  const changeDate = (date, dateString) => {
    console.log(date, dateString)
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto h-full flex flex-col px-5 py-5 bg-gray-800 items-center justify-center space-y-10 text-white">
        <div className="flex w-full space-x-10 justify-center lg:justify-start">
          <div className="w-20 h-20 bg-gray-200" />
          <div className="w-20 h-20 bg-gray-200" />
        </div>
        <p className="font-bold text-xl md:text-2xl lg:text-3xl text-center tracking-wide">
          Pendaftaran Pengguna Flipped Learning
        </p>
        <div className="flex flex-col w-[80%] md:w-[30%] space-y-4">
          <Form
            name="registerForm"
            initialValues={{
              remember: true
            }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <p className="text-white text-base font-medium mb-0">
              Nama Lengkap
            </p>
            <Form.Item
              name="nama"
              rules={[
                {
                  required: true,
                  message: 'Mohon masukkan nama lengkap Anda!'
                }
              ]}
            >
              <Input placeholder="Nama Lengkap" />
            </Form.Item>

            <p className="text-white text-base font-medium mb-0">Email</p>
            <Form.Item
              name="email"
              rules={[
                {
                  type: 'email',
                  message: 'Mohon masukkan email yang valid!'
                },
                {
                  required: true,
                  message: 'Mohon masukkan email aktif Anda!'
                }
              ]}
            >
              <Input placeholder="Email" />
            </Form.Item>

            <p className="text-white text-base font-medium mb-0">
              Jenis Kelamin
            </p>
            <Form.Item
              name="kelamin"
              rules={[
                {
                  required: true,
                  message: 'Pilih jenis kelamin Anda!'
                }
              ]}
            >
              <Select placeholder="Jenis Kelamin">
                <Select.Option value="Laki-laki">Laki</Select.Option>
                <Select.Option value="Perempuan">Perempuan</Select.Option>
              </Select>
            </Form.Item>

            <p className="text-white text-base font-medium mb-0">
              Tanggal Lahir
            </p>
            <Form.Item
              name="dob"
              rules={[
                {
                  required: true,
                  message: 'Masukkan tanggal lahir Anda!'
                }
              ]}
            >
              <DatePicker
                onChange={changeDate}
                className="w-full"
                placeholder="Tanggal Lahir"
              />
            </Form.Item>

            <p className="text-white text-base font-medium mb-0">Alamat</p>
            <Form.Item
              name="address"
              rules={[
                {
                  required: true,
                  message: 'Mohon masukkan data alamat Anda!'
                }
              ]}
            >
              <Input placeholder="Alamat" />
            </Form.Item>

            <p className="text-white text-base font-medium mb-0">Password</p>
            <Form.Item
              name="password"
              rules={[
                {
                  required: true,
                  message: 'Please input your password!'
                }
              ]}
            >
              <Input.Password placeholder="Password" />
            </Form.Item>

            <p className="text-white text-base font-medium mb-0">
              Konfirmasi Password
            </p>
            <Form.Item
              name="confirm_password"
              rules={[
                {
                  required: true,
                  message: 'Please input your password!'
                }
              ]}
            >
              <Input.Password placeholder="Konfirmasi Password" />
            </Form.Item>

            <div className="flex flex-row items-start justify-start space-x-4 text-white">
              <Form.Item name="agree" valuePropName="checked">
                <Checkbox />
              </Form.Item>
              <p className="text-sm justify-center text-justify">
                Dengan mencentang kotak ini, saya menyetujui{' '}
                <span className="font-bold hover:text-blue-500 duration-150 cursor-pointer">
                  Ketentuan Penggunaan
                </span>{' '}
                dan{' '}
                <span className="font-bold hover:text-blue-500 duration-150 cursor-pointer">
                  Kebijakan Privasi
                </span>{' '}
                Flipped Learning.
              </p>
            </div>

            <Form.Item>
              <Button type="primary" htmlType="submit" className="w-full">
                Daftar Flipped Learning
              </Button>
            </Form.Item>

            <div className="flex flex-col space-y-2 items-center text-white">
              <p className="text-base font-semibold mb-0">Kembali ke Login</p>
            </div>
          </Form>
        </div>
      </main>
    </div>
  )
}
