export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as ForgotPassword } from './ForgotPassword'
export { default as AddStudent } from './AddStudent'
export { default as AddTeacher } from './AddTeacher'
export { default as EditStudent } from './EditStudent'
export { default as EditTeacher } from './EditTeacher'
