export { default as DashboardPage } from './DashboardPage'
export { default as ManagementClassPage } from './class/ManagementClassPage'
export { default as ManagementStudentPage } from './student/ManagementStudentPage'
export { default as ClassDetailPage } from './class/ClassDetailPage'
export { default as StudentDetailPage } from './student/StudentDetailPage'
export { default as EditStudentPage } from './student/EditStudentPage'
export { default as ManagementTeacherPage } from './teacher/ManagementTeacherPage'
export { default as TeacherDetailPage } from './teacher/TeacherDetailPage'
